version: "3.2"
services:
  backend:
    build:
      context: ./backend
    ports:
    - 8090:8090
    restart: always
    volumes:
    - ./backend:/server/app
    command: php ./artisan serve --port=8090 --host=0.0.0.0
  apollo-server:
    image: nobodyiam/apollo-quick-start
    container_name: apollo-server
    depends_on:
    - apollo-db
    ports:
    - "8080:8080"
    - "8070:8070"
    links:
    - apollo-db
  apollo-db:
    image: mysql:5.7
    container_name: apollo-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
    - apollo-dbdata
    ports:
    - "13306:3306"
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    volumes_from:
    - apollo-dbdata
  apollo-dbdata:
    image: alpine:latest
    container_name: apollo-dbdata
    volumes:
    - /var/lib/mysql